# Generated by Django 3.1.6 on 2021-09-28 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAdm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=12)),
                ('foto', models.ImageField(null=True, upload_to='PerAD/%Y/%m/%d/')),
                ('cargo', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('direccion', models.TextField(max_length=100)),
                ('teln_Casa', models.CharField(max_length=11)),
                ('teln_movil', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Personal Administrativo',
                'verbose_name_plural': 'Personal Administrativos',
            },
        ),
        migrations.CreateModel(
            name='PersonalDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=12)),
                ('foto', models.ImageField(null=True, upload_to='PerDO/%Y/%m/%d/')),
                ('materia', models.IntegerField(choices=[(1, 'Lenguaje'), (2, 'Comunicación y Cultura'), (3, 'Ciencias Naturales y Sociedad'), (4, 'Ciencias Sociales'), (5, 'Ciudadanía e Identidad'), (6, 'Educación Física, deporte y Recreación'), (7, 'Matemática')], default=1)),
                ('especialidades', models.IntegerField(choices=[(1, 'Desarrollo Endogeno'), (2, 'Educación Física'), (3, 'Música'), (4, 'Teatro'), (5, 'Danza'), (6, 'Manualidades'), (7, 'Aula Integrada'), (8, 'Producción'), (9, 'CRA (Centro de Recursos para el Aprendizaje)')], default=1)),
                ('edad', models.IntegerField()),
                ('direccion', models.TextField(max_length=100)),
                ('teln_Casa', models.CharField(max_length=11)),
                ('teln_movil', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Personal Docente',
                'verbose_name_plural': 'Personal Docentes',
            },
        ),
        migrations.CreateModel(
            name='Representantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=12)),
                ('foto', models.ImageField(null=True, upload_to='REP/%Y/%m/%d/')),
                ('edad', models.IntegerField()),
                ('direccion', models.TextField(max_length=100)),
                ('teln_Casa', models.CharField(max_length=11)),
                ('teln_movil', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=12)),
                ('foto', models.ImageField(null=True, upload_to='EST/%Y/%m/%d/')),
                ('edad', models.IntegerField()),
                ('altura', models.FloatField(max_length=5)),
                ('peso', models.FloatField(max_length=5)),
                ('talla_zapato', models.IntegerField()),
                ('talla_camisa', models.CharField(max_length=2)),
                ('talla_pantalon', models.IntegerField()),
                ('grado', models.IntegerField(choices=[(1, '1ero'), (2, '2do'), (3, '3ro'), (4, '4to'), (5, '5to'), (6, '6to')], default=1)),
                ('seccion', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'F'), (7, 'G'), (8, 'H')], default=1)),
                ('fecha_nac', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('Rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.representantes')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
    ]
