# Generated by Django 3.1.6 on 2021-06-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Documento', models.CharField(max_length=30)),
                ('Documento', models.FileField(null=True, upload_to='uploads/Docs/%Y/%m/%d/')),
                ('Tipo', models.IntegerField(choices=[(1, 'Boletin'), (2, 'Constancia'), (3, 'Planilla'), (4, 'Convocatoria'), (5, 'Otro')], default=2, null=True)),
                ('Formato', models.IntegerField(choices=[(1, 'Word'), (2, 'Excel'), (3, 'PowerPoint'), (4, 'PDF'), (5, 'LibreOffice'), (6, 'Otro')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento Administrativo',
                'verbose_name_plural': 'Documentos Administrativos',
            },
        ),
        migrations.CreateModel(
            name='NotasDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grado', models.CharField(max_length=2)),
                ('Seccion', models.CharField(max_length=2)),
                ('Documento', models.FileField(null=True, upload_to='uploads/Notas/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
