# Generated by Django 3.1.6 on 2021-11-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0003_auto_20211116_1234'),
        ('gestionDocumentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsdb',
            name='PA_Docs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Institucion.pa_profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notasdb',
            name='Momento',
            field=models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III')], default=1),
        ),
        migrations.AddField(
            model_name='notasdb',
            name='Nombre_Notas',
            field=models.CharField(default='NULO', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notasdb',
            name='PD_Notes',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Institucion.pd_profile'),
            preserve_default=False,
        ),
    ]
