# Generated by Django 3.1.6 on 2022-05-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDocumentos', '0002_auto_20211116_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notasdb',
            name='Nombre_Notas',
            field=models.CharField(max_length=250),
        ),
    ]
