# Generated by Django 3.1.6 on 2021-09-28 22:21

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'Un Usuario ya está registrado con este nombre de Usuario'}, help_text='Requiere. 30 Caracteres o menos. Entre: Letras, digitos númericos and @/./+/-/_ solamente.', max_length=30, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email del Usuario')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Estado de Administrador')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Activado')),
                ('is_PA', models.BooleanField(default=False, help_text='Esta opcion, permite el acceso a Usuario de tipo PA: Personal Administrativo', verbose_name='Estado de Usuario PA')),
                ('is_PD', models.BooleanField(default=False, help_text='Esta opcion, permite el acceso a Usuario de tipo PD: Personal Docente', verbose_name='Estado de Usuario PD')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PD_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=12)),
                ('foto', models.ImageField(null=True, upload_to='PerAD/%Y/%m/%d/')),
                ('materia', models.IntegerField(choices=[(1, 'Lenguaje'), (2, 'Comunicación y Cultura'), (3, 'Ciencias Naturales y Sociedad'), (4, 'Ciencias Sociales'), (5, 'Ciudadanía e Identidad'), (6, 'Educación Física, deporte y Recreación'), (7, 'Matemática')], default=1)),
                ('especialidades', models.IntegerField(choices=[(1, 'Desarrollo Endogeno'), (2, 'Educación Física'), (3, 'Música'), (4, 'Teatro'), (5, 'Danza'), (6, 'Manualidades'), (7, 'Aula Integrada'), (8, 'Producción'), (9, 'CRA (Centro de Recursos para el Aprendizaje)')], default=1)),
                ('edad', models.IntegerField()),
                ('direccion', models.TextField(max_length=100)),
                ('teln_Casa', models.CharField(max_length=11)),
                ('teln_movil', models.CharField(max_length=11)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Docente2',
                'verbose_name_plural': 'Personal Docentes2',
            },
        ),
        migrations.CreateModel(
            name='PA_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=12, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='PerAD/%Y/%m/%d/')),
                ('cargo', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('direccion', models.TextField(max_length=100)),
                ('teln_Casa', models.CharField(max_length=11)),
                ('teln_movil', models.CharField(max_length=11)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Administrativo2',
                'verbose_name_plural': 'Personal Administrativos2',
            },
        ),
    ]
