# Generated by Django 3.1.6 on 2021-06-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='user_type',
            field=models.CharField(default='0', max_length=2, verbose_name='user_type'),
        ),
    ]
