# Generated by Django 3.1.6 on 2021-11-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pd_profile',
            name='cedula',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
