# Generated by Django 3.1.6 on 2021-11-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0002_auto_20211104_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pa_profile',
            options={'verbose_name': 'Perfil del Administrativo', 'verbose_name_plural': 'Perfiles del Administrativo'},
        ),
        migrations.AlterModelOptions(
            name='pd_profile',
            options={'verbose_name': 'Perfil del Personal Docente', 'verbose_name_plural': 'Perfiles del Personal Docente'},
        ),
    ]
