# Generated by Django 3.1.6 on 2022-05-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0004_auto_20220530_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pd_profile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='PerDo/%Y/%m/%d/'),
        ),
    ]
